### ISSUE TITLE
ontap plugin - got KeyError: 'size-total'

### ISSUE THREAD

**Issue by tasleson** [libstorage/libstoragemgmt#301] opened 2017-09-06 19:34 UTC
https://bugzilla.redhat.com/show_bug.cgi?id=1488085

**Comment by cathay4t** [comment] 2017-09-19 14:25
Closing since the reporter failed to reproduce this issue and NetApp API document indicate the `size-total` key is mandatory

**Closed by cathay4t** 2017-09-19 14:25 UTC
Labels: bug
