### ISSUE TITLE
PLUGIN_BUG(2): Expected key missing from SmartArray hpssacli output:'Disk Name'

### ISSUE THREAD

**Issue by cvedel** [libstorage/libstoragemgmt#167] opened 2016-07-11 12:55 UTC
I get this message running the following command when a logical disk is failed:

`lsmcli -u hpsa:// lv`

AFAICS, the output of hpssacli does not contain the 'Disk Name' field in this case so that _hp_ld_to_lsm_vol fails with a KeyError at:

`device = Device.from_device_file(_CONTEXT, hp_ld['Disk Name'])` 

A failed logical disk should not break the listing and it should still be listed so that it can be re-enabled once the physical disk has been replaced, i.e. this case is not equivalent to a DeviceNotFoundError.

Thanks

**Comment by joehandzik** [comment] 2016-07-11 13:16
You are definitely correct, @cvedel. It looks like hpssacli drops the /dev path when a disk is failed (at least for your version of hpssacli). Can you reply back with the version of hpssacli that you're using (should be a -v argument or something similar)?

I'm a little concerned because I thought I had run through this exact scenario, but it's possible that I didn't. And, in my experience, device paths stay present for logical volumes even after they have failed on a Smart Array. So...I'm not entirely sure *why* the underlying tool would stop reporting the path.

**Comment by cathay4t** [comment] 2016-07-11 13:24
@joehandzik I believe we should use VPD83 to find out the disk name via `lsm.LocalDisk.vpd83_search()` instead of depending hpssacli doing so.

**Comment by joehandzik** [comment] 2016-07-11 13:33
@cathay4t Probably the most correct fix to move us away from using hpssacli wherever possible, yep. I'll give that change a shot and see if it works for @cvedel.

**Comment by cvedel** [comment] 2016-07-12 06:36
I am using version 2.40.13.0 with a Smart Array P420i:

    # hpssacli version

     HPSSACLI Version: 2.40.13.0
     SOULAPI Version: 8.4.13.0


The output of hpssacli for the failed logical drive is:

      Array: N
      Interface Type: Solid State SATA
      Unused Space: 0  MB (0.0%)
      Used Space: 3.6 TB (100.0%)
      Status: Failed Physical Drive
      Array Type: Data       HPE SSD Smart Path: disable

      Warning: One of the drives on this array have failed or has been removed.




      Logical Drive: 15
         Size: 3.6 TB
         Fault Tolerance: 0
         Heads: 255
         Sectors Per Track: 32
         Cylinders: 65535
         Strip Size: 256 KB
         Full Stripe Size: 256 KB
         Status: Failed
         Caching:  Enabled
         Unique Identifier: 600508B1001C58094D89C2D1449B5F6C
         Logical Drive Label: 38EB0E9FPCFBB%%LM6S1CG7674
         Drive Type: Data
         LD Acceleration Method: Controller Cache

      physicaldrive 2I:1:15
         Port: 2I
         Box: 1
         Bay: 15
         Status: Failed
         Last Failure Reason: Init replacement too small
         Drive Type: Data Drive
         Interface Type: Solid State SATA
         Size: 480.1 GB
         Drive exposed to OS: False
         Native Block Size: 512
         Firmware Revision: 4IWVHPG1
         Serial Number: BTWL417501T6480QGN
         Model: ATA     VK0480GDJXV
         SATA NCQ Capable: True
         SATA NCQ Enabled: True
         Usage remaining: 91.74%
         Power On Hours: 12198
         Estimated Life Remaining based on workload to date: 5644 days
         SSD Smart Trip Wearout: False
         PHY Count: 1
         PHY Transfer Rate: 6.0Gbps
         Drive Authentication Status: Not Applicable
         Sanitize Erase Supported: False

As you can see, an SSD was put in the slot that was occupied by an HDD. I am not sure why this happened in our lab (I am not the only one using it and have no physical access) but this could happen because of human errors so I think we should handle this case.

**Comment by cathay4t** [comment] 2016-07-21 05:13
@cvedel Issue has been fixed in commit 553770fb002ef24429a86f816986d74297ef69f2. Please try our [weekly snapshot build][1] to verify that.
I am closing this issue as I have reproduced this problem and confirmed fix.
Please feel free to open another issue if it does not works on you.

[1]: https://libstorage.github.io/libstoragemgmt-doc/doc/install.html#weekly-snapshot-build

**Closed by cathay4t** 2016-07-21 05:13 UTC
Labels: bug

**Comment by cvedel** [comment] 2016-07-21 15:31
I have problems with my lab at the moment but will test ASAP.

Thanks
